name: npmjs

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '18', '20' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm test
      - if: github.event_name == 'release' && github.event.action == 'published' && matrix.node == '16'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
